name: ci

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: {}

jobs:
  test-python:
    name: Test ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: pip install -r tests/requirements.txt

      - name: Build/Install toussaint
        run: pip install -e .

      - name: Run Tests
        run: pytest
